#!/bin/sh

SKIN_DIR="/usr/share/enigma2/Simple_Ten_Eighty"
PLUGIN_SKIN_DIR="/usr/lib/enigma2/python/Plugins/Extensions/SamsungTV/skin"

if [ -f "$SKIN_DIR/skin_plugins.xml" ] && [ -f "$PLUGIN_SKIN_DIR/Simple_Ten_Eighty/SamsungTV.xml" ]; then
    if ! grep -q '<screen name="SamsungTV"' "$SKIN_DIR/skin_plugins.xml"; then
        sed -i 's/<\/skin>//' "$SKIN_DIR/skin_plugins.xml"
        cat "$PLUGIN_SKIN_DIR/Simple_Ten_Eighty/SamsungTV.xml" >> "$SKIN_DIR/skin_plugins.xml"
        echo '</skin>' >> "$SKIN_DIR/skin_plugins.xml"
        echo "SamsungTV skin added to Simple_Ten_Eighty skin_plugins.xml."
    fi
fi

cp $PLUGIN_SKIN_DIR/samsungtv-backdrop.jpg $SKIN_DIR/extensions/samsungtv-backdrop.jpg

echo "***********************************"
echo "*           SamsungTV             *"
echo "*              by                 *"
echo "*           xentaurix             *"
echo "***********************************"
echo ""
echo "Plugin Samsung TV Plus installed successfully."
echo "Please restart Enigma2 now!"
echo ""

exit 0
